baseURL: 'http://dims.sh'
languageCode: 'en-us'
title: 'dims.sh'
theme: 'dims-theme'
params:
  mainSections:
    - posts
    - trading-journal
  homeInfoParams:
    Title: Hi there! I am Dimas
    Content: A software dev, web3 enthusiast and open source contributor
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/dimasriat"
    - name: "twitter"
      url: "https://x.com/0xDimss"

taxonomies:
  tag: "tags"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags
      weight: 2

# https://github.com/M1cR0xf7/kaslaanka?tab=readme-ov-file#configtoml
