baseURL = 'https://dims.sh'
languageCode = 'en-us'
title = 'dims.sh'
theme = 'kaslaanka'

[params]
sitename = "dimasriat"
copyrights = "dimasriat"
defaultList = "global"
paginationLen = 3
projectsURL = "https://dims.sh"
brief_about = "<center>A software developer, open source contributor and crypto trader.</center>"

[taxonomies]
tag = "tags"
trading = "trading"
dev = "dev"

[[menu.primary]]
name = "Home"
url = "/"
weight = 1

[[menu.primary]]
name = "About"
url = "/about"
weight = 2

[[menu.primary]]
name = "Tags"
url = "/tags"
weight = 3

# https://github.com/M1cR0xf7/kaslaanka?tab=readme-ov-file#configtoml
