baseURL = 'https://dims.sh'
languageCode = 'en-us'
title = 'dims.sh'
theme = 'kaslaanka'

[params]
sitename = "Dimas Riatmodjo"
copyrights = "Dimas Riatmodjo"
defaultList = "global"
paginationLen = 3
projectsURL = "https://dims.sh"
brief_about = "<center>A software developer and open source contributor.</center>"

# https://github.com/M1cR0xf7/kaslaanka?tab=readme-ov-file#configtoml
